-- 基于TOGAF业务架构分析的数据库设计补充
-- 新增缺失的重要业务实体表

-- 1. 用户偏好表
CREATE TABLE T_USER_PREFERENCE (
    PREFERENCE_ID VARCHAR(32) PRIMARY KEY COMMENT '偏好ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    NOTIFICATION_CARE_REMIND BOOLEAN DEFAULT TRUE COMMENT '养护提醒通知',
    NOTIFICATION_COMMUNITY BOOLEAN DEFAULT TRUE COMMENT '社区互动通知',
    NOTIFICATION_AI_RESPONSE BOOLEAN DEFAULT TRUE COMMENT 'AI回复通知',
    PRIVACY_PROFILE_VISIBLE BOOLEAN DEFAULT TRUE COMMENT '个人资料可见性',
    PRIVACY_PLANT_VISIBLE BOOLEAN DEFAULT TRUE COMMENT '植物信息可见性',
    INTERFACE_THEME VARCHAR(32) DEFAULT 'AUTO' COMMENT '界面主题（LIGHT/DARK/AUTO）',
    PREFERRED_PLANT_TYPES VARCHAR(512) COMMENT '偏好植物类型（逗号分隔）',
    CARE_REMIND_FREQUENCY INT DEFAULT 3 COMMENT '养护提醒频率（天）',
    LOCATION_SHARING BOOLEAN DEFAULT FALSE COMMENT '位置信息分享',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE KEY uk_user_preference(OPENID),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID)
);

-- 2. 植物类型表（标准化植物分类）
CREATE TABLE T_PLANT_TYPE (
    TYPE_ID VARCHAR(32) PRIMARY KEY COMMENT '类型ID',
    TYPE_NAME VARCHAR(128) NOT NULL COMMENT '植物类型名称',
    SCIENTIFIC_NAME VARCHAR(256) COMMENT '学名',
    FAMILY_NAME VARCHAR(128) COMMENT '科名',
    GENUS_NAME VARCHAR(128) COMMENT '属名',
    COMMON_NAMES VARCHAR(512) COMMENT '常见别名（逗号分隔）',
    DESCRIPTION TEXT COMMENT '植物描述',
    CARE_DIFFICULTY VARCHAR(32) DEFAULT 'MEDIUM' COMMENT '养护难度（EASY/MEDIUM/HARD）',
    LIGHT_REQUIREMENT VARCHAR(32) COMMENT '光照需求（FULL_SUN/PARTIAL_SUN/SHADE）',
    WATER_REQUIREMENT VARCHAR(32) COMMENT '水分需求（LOW/MEDIUM/HIGH）',
    TEMPERATURE_MIN INT COMMENT '最低温度要求',
    TEMPERATURE_MAX INT COMMENT '最高温度要求',
    HUMIDITY_REQUIREMENT VARCHAR(32) COMMENT '湿度需求（LOW/MEDIUM/HIGH）',
    SOIL_TYPE VARCHAR(128) COMMENT '土壤类型要求',
    GROWTH_SEASON VARCHAR(64) COMMENT '生长季节',
    FLOWERING_SEASON VARCHAR(64) COMMENT '开花季节',
    TYPICAL_HEIGHT VARCHAR(64) COMMENT '典型高度',
    PROPAGATION_METHODS VARCHAR(256) COMMENT '繁殖方法',
    COMMON_DISEASES VARCHAR(512) COMMENT '常见病害',
    COMMON_PESTS VARCHAR(512) COMMENT '常见虫害',
    REFERENCE_IMAGE VARCHAR(512) COMMENT '参考图片',
    IS_TOXIC BOOLEAN DEFAULT FALSE COMMENT '是否有毒',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_plant_type_name(TYPE_NAME),
    INDEX idx_plant_family(FAMILY_NAME),
    INDEX idx_care_difficulty(CARE_DIFFICULTY)
);

-- 3. 养护类型表（标准化养护操作）
CREATE TABLE T_CARE_TYPE (
    CARE_TYPE_ID VARCHAR(32) PRIMARY KEY COMMENT '养护类型ID',
    TYPE_NAME VARCHAR(64) NOT NULL COMMENT '养护类型名称',
    TYPE_CODE VARCHAR(32) NOT NULL COMMENT '类型代码',
    DESCRIPTION VARCHAR(512) COMMENT '类型描述',
    ICON_URL VARCHAR(256) COMMENT '图标URL',
    DEFAULT_FREQUENCY INT COMMENT '默认频率（天）',
    SEASONAL_ADJUSTMENT VARCHAR(1024) COMMENT '季节调整说明（JSON格式）',
    OPERATION_GUIDE TEXT COMMENT '操作指南',
    REQUIRED_TOOLS VARCHAR(256) COMMENT '所需工具',
    BEST_TIME VARCHAR(128) COMMENT '最佳操作时间',
    PRECAUTIONS VARCHAR(512) COMMENT '注意事项',
    DIFFICULTY_LEVEL VARCHAR(32) DEFAULT 'EASY' COMMENT '操作难度（EASY/MEDIUM/HARD）',
    CATEGORY VARCHAR(32) NOT NULL COMMENT '大类（BASIC/ADVANCED/EMERGENCY）',
    SORT_ORDER INT DEFAULT 0 COMMENT '排序顺序',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE KEY uk_care_type_code(TYPE_CODE),
    INDEX idx_care_category(CATEGORY),
    INDEX idx_care_difficulty(DIFFICULTY_LEVEL)
);

-- 4. AI识别结果表（详细的识别结果）
CREATE TABLE T_IDENTIFICATION_RESULT (
    RESULT_ID VARCHAR(32) PRIMARY KEY COMMENT '识别结果ID',
    CONSULTATION_ID VARCHAR(32) NOT NULL COMMENT '咨询ID',
    PLANT_TYPE_ID VARCHAR(32) COMMENT '识别的植物类型ID',
    CONFIDENCE_SCORE DECIMAL(5,4) COMMENT '置信度分数（0-1）',
    ALTERNATIVE_RESULTS TEXT COMMENT '备选结果（JSON格式）',
    IDENTIFIED_FEATURES VARCHAR(1024) COMMENT '识别的特征点',
    ANALYSIS_DETAILS TEXT COMMENT '分析详情（JSON格式）',
    PROCESSING_TIME INT COMMENT '处理时间（毫秒）',
    AI_MODEL_VERSION VARCHAR(64) COMMENT 'AI模型版本',
    IMAGE_QUALITY_SCORE DECIMAL(3,2) COMMENT '图片质量评分',
    RECOMMENDED_ACTIONS VARCHAR(512) COMMENT '推荐操作',
    CARE_SUGGESTIONS TEXT COMMENT '养护建议',
    WARNING_NOTES VARCHAR(512) COMMENT '警告说明',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_consultation_result(CONSULTATION_ID),
    INDEX idx_plant_type_result(PLANT_TYPE_ID),
    INDEX idx_confidence_score(CONFIDENCE_SCORE),
    FOREIGN KEY (CONSULTATION_ID) REFERENCES T_AI_CONSULTATION(CONSULTATION_ID),
    FOREIGN KEY (PLANT_TYPE_ID) REFERENCES T_PLANT_TYPE(TYPE_ID)
);

-- 5. 养护计划表（AI生成的个性化养护计划）
CREATE TABLE T_CARE_PLAN (
    PLAN_ID VARCHAR(32) PRIMARY KEY COMMENT '计划ID',
    PLANT_ID VARCHAR(32) NOT NULL COMMENT '植物ID',
    PLANT_TYPE_ID VARCHAR(32) COMMENT '植物类型ID',
    PLAN_NAME VARCHAR(128) COMMENT '计划名称',
    PLAN_DESCRIPTION VARCHAR(512) COMMENT '计划描述',
    START_DATE DATE NOT NULL COMMENT '开始日期',
    END_DATE DATE COMMENT '结束日期',
    SEASON VARCHAR(32) COMMENT '适用季节',
    CARE_SCHEDULE TEXT COMMENT '养护时间表（JSON格式）',
    WEEKLY_TASKS TEXT COMMENT '每周任务（JSON格式）',
    MONTHLY_TASKS TEXT COMMENT '每月任务（JSON格式）',
    SPECIAL_NOTES VARCHAR(1024) COMMENT '特殊说明',
    DIFFICULTY_LEVEL VARCHAR(32) DEFAULT 'MEDIUM' COMMENT '计划难度',
    ESTIMATED_TIME_PER_WEEK INT COMMENT '每周预计耗时（分钟）',
    SUCCESS_INDICATORS VARCHAR(512) COMMENT '成功指标',
    PLAN_STATUS VARCHAR(32) DEFAULT 'ACTIVE' COMMENT '计划状态（ACTIVE/PAUSED/COMPLETED）',
    COMPLETION_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '完成率（百分比）',
    AI_GENERATED BOOLEAN DEFAULT TRUE COMMENT '是否AI生成',
    LAST_UPDATED_BY VARCHAR(32) COMMENT '最后更新方式（AI/USER）',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_plant_plan(PLANT_ID),
    INDEX idx_plant_type_plan(PLANT_TYPE_ID),
    INDEX idx_plan_status(PLAN_STATUS, START_DATE),
    FOREIGN KEY (PLANT_ID) REFERENCES T_USER_PLANT(PLANT_ID),
    FOREIGN KEY (PLANT_TYPE_ID) REFERENCES T_PLANT_TYPE(TYPE_ID)
);

-- 6. AI模型配置表
CREATE TABLE T_AI_MODEL_CONFIG (
    CONFIG_ID VARCHAR(32) PRIMARY KEY COMMENT '配置ID',
    MODEL_NAME VARCHAR(128) NOT NULL COMMENT '模型名称',
    MODEL_TYPE VARCHAR(64) NOT NULL COMMENT '模型类型（IDENTIFICATION/CONSULTATION/RECOMMENDATION）',
    MODEL_VERSION VARCHAR(64) COMMENT '模型版本',
    API_ENDPOINT VARCHAR(256) COMMENT 'API端点',
    API_KEY_NAME VARCHAR(128) COMMENT 'API密钥名称',
    MODEL_PARAMETERS TEXT COMMENT '模型参数（JSON格式）',
    MAX_REQUESTS_PER_DAY INT DEFAULT 1000 COMMENT '每日最大请求数',
    TIMEOUT_SECONDS INT DEFAULT 30 COMMENT '超时时间（秒）',
    RETRY_ATTEMPTS INT DEFAULT 3 COMMENT '重试次数',
    CONFIDENCE_THRESHOLD DECIMAL(3,2) DEFAULT 0.6 COMMENT '置信度阈值',
    IS_PRIMARY BOOLEAN DEFAULT FALSE COMMENT '是否主要模型',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    COST_PER_REQUEST DECIMAL(10,6) COMMENT '每次请求成本',
    PERFORMANCE_METRICS TEXT COMMENT '性能指标（JSON格式）',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_model_type(MODEL_TYPE, IS_ACTIVE),
    INDEX idx_primary_model(IS_PRIMARY, MODEL_TYPE)
);

-- 7. 更新原有表结构（添加外键关联）
-- 为T_USER_PLANT表添加植物类型外键
ALTER TABLE T_USER_PLANT 
ADD COLUMN PLANT_TYPE_ID VARCHAR(32) COMMENT '植物类型ID',
ADD INDEX idx_plant_type_id(PLANT_TYPE_ID);

-- 为T_CARE_RECORD表添加养护类型外键
ALTER TABLE T_CARE_RECORD 
ADD COLUMN CARE_TYPE_ID VARCHAR(32) COMMENT '养护类型ID',
ADD INDEX idx_care_type_id(CARE_TYPE_ID);

-- 插入基础养护类型数据
INSERT INTO T_CARE_TYPE VALUES
('CARE_001', '浇水', 'WATER', '为植物提供水分', '/icons/water.png', 3, '{"spring":2,"summer":1,"autumn":3,"winter":5}', '检查土壤湿度，适量浇水至土壤湿润', '浇水壶', '早晨或傍晚', '避免积水，注意水温', 'EASY', 'BASIC', 1, TRUE, NOW(), NOW()),
('CARE_002', '施肥', 'FERTILIZE', '为植物提供营养', '/icons/fertilize.png', 14, '{"spring":7,"summer":10,"autumn":14,"winter":30}', '选择合适肥料，按比例稀释后施用', '肥料、量杯', '生长季节', '避免过量，注意肥料类型', 'MEDIUM', 'BASIC', 2, TRUE, NOW(), NOW()),
('CARE_003', '修剪', 'PRUNE', '修剪枯叶和多余枝条', '/icons/prune.png', 7, '{"spring":5,"summer":7,"autumn":10,"winter":14}', '使用干净工具，修剪枯黄叶片和病枝', '修剪剪、消毒液', '任何时间', '工具要消毒，伤口要处理', 'MEDIUM', 'BASIC', 3, TRUE, NOW(), NOW()),
('CARE_004', '观察记录', 'OBSERVE', '观察植物生长状态', '/icons/observe.png', 1, '{"spring":1,"summer":1,"autumn":1,"winter":2}', '仔细观察植物叶片、茎干、根部状态', '放大镜（可选）', '任何时间', '注意病虫害征象', 'EASY', 'BASIC', 4, TRUE, NOW(), NOW()),
('CARE_005', '换盆', 'REPOT', '更换更大的花盆', '/icons/repot.png', 365, '{"spring":180,"summer":365,"autumn":365,"winter":365}', '选择合适大小花盆，小心移植', '新花盆、土壤、铲子', '春季最佳', '避免伤根，注意排水', 'HARD', 'ADVANCED', 5, TRUE, NOW(), NOW());

-- 插入基础植物类型数据（示例）
INSERT INTO T_PLANT_TYPE VALUES
('PLANT_001', '绿萝', 'Epipremnum aureum', '天南星科', '绿萝属', '黄金葛,魔鬼藤', '常见的室内观叶植物，叶片心形，生长迅速', 'EASY', 'PARTIAL_SUN', 'MEDIUM', 15, 30, 'MEDIUM', '疏松透气', '全年', '很少开花', '1-3米', '扦插', '根腐病,叶斑病', '蚜虫,红蜘蛛', '/images/plants/pothos.jpg', FALSE, TRUE, NOW(), NOW()),
('PLANT_002', '吊兰', 'Chlorophytum comosum', '百合科', '吊兰属', '折鹤兰,挂兰', '叶片细长，容易繁殖，适合悬挂种植', 'EASY', 'PARTIAL_SUN', 'MEDIUM', 10, 28, 'MEDIUM', '疏松肥沃', '春夏', '夏季', '20-40厘米', '分株,播种', '叶枯病', '蚜虫', '/images/plants/spider_plant.jpg', FALSE, TRUE, NOW(), NOW()),
('PLANT_003', '仙人掌', 'Cactaceae', '仙人掌科', '仙人掌属', '仙人球', '多肉植物，耐旱性强，形态多样', 'EASY', 'FULL_SUN', 'LOW', 5, 40, 'LOW', '沙质土壤', '春夏', '春夏', '5厘米-5米', '扦插,播种', '软腐病', '介壳虫', '/images/plants/cactus.jpg', FALSE, TRUE, NOW(), NOW());