-- 基于个人用户+免费公益+全国性服务的数据库优化方案

-- 1. 用户表优化（增加地区信息）
ALTER TABLE T_WECHAT_CUSTOMER 
ADD COLUMN REGION_CODE VARCHAR(10) COMMENT '用户所在地区代码',
ADD COLUMN USER_LEVEL INT DEFAULT 1 COMMENT '用户等级',
ADD COLUMN TOTAL_PLANTS INT DEFAULT 0 COMMENT '认领植物总数',
ADD COLUMN ACTIVE_DAYS INT DEFAULT 0 COMMENT '活跃天数';

-- 2. 植物表重命名和优化
-- 将 T_WECHAT_PET 重命名为 T_WECHAT_PLANT
-- 将相关字段从"物品"改为"植物"
ALTER TABLE T_WECHAT_PET RENAME TO T_WECHAT_PLANT;
ALTER TABLE T_WECHAT_PLANT 
CHANGE OBJECT_TYPE PLANT_TYPE VARCHAR(32) COMMENT '植物大类',
CHANGE OBJECT_CLASS PLANT_CLASS VARCHAR(32) COMMENT '植物细类',
CHANGE OBJECT_NUMBER PLANT_NUMBER VARCHAR(32) COMMENT '植物编号',
CHANGE OBJECT_NAME PLANT_NAME VARCHAR(128) COMMENT '植物名称',
CHANGE OBJECT_DISCRIPTION PLANT_DESCRIPTION VARCHAR(1024) COMMENT '植物介绍',
CHANGE OBJECT_REMARK PLANT_REMARK VARCHAR(1024) COMMENT '植物备注',
CHANGE OBJECT_SCAN_INDEX PLANT_QR_CODE VARCHAR(128) COMMENT '植物二维码',
CHANGE OBJECT_PRICE_INDEX CARE_DIFFICULTY VARCHAR(32) COMMENT '养护难度',
CHANGE OBJECT_IMAGE_INDEX PLANT_IMAGES VARCHAR(1024) COMMENT '植物图片',
CHANGE OBJECT_CHANNEL_INDEX KNOWLEDGE_LINK VARCHAR(128) COMMENT '知识链接',
CHANGE OBJECT_STATUS PLANT_STATUS VARCHAR(32) COMMENT '植物状态';

-- 添加植物相关字段
ALTER TABLE T_WECHAT_PLANT
ADD COLUMN SUITABLE_REGION VARCHAR(128) COMMENT '适宜地区',
ADD COLUMN CARE_TIPS VARCHAR(1024) COMMENT '养护要点',
ADD COLUMN GROWTH_CYCLE INT COMMENT '生长周期(天)',
ADD COLUMN WATER_FREQUENCY INT COMMENT '浇水频率(天)',
ADD COLUMN SUNLIGHT_NEED VARCHAR(32) COMMENT '光照需求',
ADD COLUMN ADOPT_COUNT INT DEFAULT 0 COMMENT '被认领次数';

-- 3. 用户认领表优化
ALTER TABLE T_WECHAT_CUST_OWNED RENAME TO T_USER_PLANT_ADOPTION;
ALTER TABLE T_USER_PLANT_ADOPTION
CHANGE OBJECT_TYPE PLANT_TYPE VARCHAR(32) COMMENT '植物大类',
CHANGE OBJECT_CLASS PLANT_CLASS VARCHAR(32) COMMENT '植物细类', 
CHANGE OBJECT_NUMBER PLANT_NUMBER VARCHAR(32) COMMENT '植物编号',
CHANGE OBJECT_NAME PLANT_NAME VARCHAR(128) COMMENT '植物名称',
CHANGE OBJECT_DISCRIPTION PLANT_DESCRIPTION VARCHAR(1024) COMMENT '植物介绍';

-- 添加认领相关字段
ALTER TABLE T_USER_PLANT_ADOPTION
ADD COLUMN ADOPTION_NAME VARCHAR(64) COMMENT '用户给植物起的名字',
ADD COLUMN CARE_SCORE INT DEFAULT 0 COMMENT '养护得分',
ADD COLUMN LAST_CARE_TIME DATETIME COMMENT '最后养护时间',
ADD COLUMN GROWTH_STAGE VARCHAR(32) DEFAULT '幼苗' COMMENT '成长阶段',
ADD COLUMN IS_HEALTHY BOOLEAN DEFAULT TRUE COMMENT '是否健康';

-- 4. 新增表结构

-- 地区管理表
CREATE TABLE T_REGION (
    REGION_CODE VARCHAR(10) PRIMARY KEY COMMENT '地区代码',
    REGION_NAME VARCHAR(50) NOT NULL COMMENT '地区名称',
    PARENT_CODE VARCHAR(10) COMMENT '父级地区代码',
    REGION_LEVEL INT NOT NULL COMMENT '地区级别 1省 2市 3区县',
    CLIMATE_TYPE VARCHAR(32) COMMENT '气候类型',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 植物知识库表
CREATE TABLE T_PLANT_KNOWLEDGE (
    KNOWLEDGE_ID VARCHAR(32) PRIMARY KEY COMMENT '知识ID',
    PLANT_TYPE VARCHAR(32) COMMENT '植物类型',
    TITLE VARCHAR(128) NOT NULL COMMENT '标题',
    CONTENT TEXT COMMENT '内容',
    IMAGES VARCHAR(1024) COMMENT '图片链接',
    AUTHOR VARCHAR(64) COMMENT '作者',
    AUTHOR_TYPE VARCHAR(32) DEFAULT 'USER' COMMENT '作者类型 USER/EXPERT/SYSTEM',
    VIEW_COUNT INT DEFAULT 0 COMMENT '浏览次数',
    LIKE_COUNT INT DEFAULT 0 COMMENT '点赞次数',
    IS_FEATURED BOOLEAN DEFAULT FALSE COMMENT '是否精选',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 用户养护记录表
CREATE TABLE T_CARE_RECORD (
    RECORD_ID VARCHAR(32) PRIMARY KEY COMMENT '记录ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    PLANT_TYPE VARCHAR(32) NOT NULL COMMENT '植物大类',
    PLANT_CLASS VARCHAR(32) NOT NULL COMMENT '植物细类',
    PLANT_NUMBER VARCHAR(32) NOT NULL COMMENT '植物编号',
    CARE_TYPE VARCHAR(32) NOT NULL COMMENT '养护类型 WATER/FERTILIZE/PRUNE/PHOTO',
    CARE_NOTE VARCHAR(512) COMMENT '养护备注',
    IMAGES VARCHAR(1024) COMMENT '照片记录',
    WEATHER VARCHAR(32) COMMENT '天气情况',
    MOOD VARCHAR(32) COMMENT '心情记录',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 用户行为记录表
CREATE TABLE T_USER_BEHAVIOR (
    BEHAVIOR_ID VARCHAR(32) PRIMARY KEY COMMENT '行为ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    BEHAVIOR_TYPE VARCHAR(32) NOT NULL COMMENT '行为类型',
    TARGET_ID VARCHAR(32) COMMENT '目标对象ID',
    TARGET_TYPE VARCHAR(32) COMMENT '目标对象类型',
    EXTRA_DATA VARCHAR(512) COMMENT '额外数据',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 系统消息表
CREATE TABLE T_SYSTEM_MESSAGE (
    MESSAGE_ID VARCHAR(32) PRIMARY KEY COMMENT '消息ID',
    OPENID VARCHAR(128) COMMENT '用户ID，为空表示全员消息',
    MESSAGE_TYPE VARCHAR(32) NOT NULL COMMENT '消息类型',
    TITLE VARCHAR(128) NOT NULL COMMENT '消息标题',
    CONTENT VARCHAR(1024) NOT NULL COMMENT '消息内容',
    LINK_URL VARCHAR(256) COMMENT '跳转链接',
    IS_READ BOOLEAN DEFAULT FALSE COMMENT '是否已读',
    SEND_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    EXPIRE_TIME DATETIME COMMENT '过期时间'
);

-- 专家用户表
CREATE TABLE T_EXPERT_USER (
    EXPERT_ID VARCHAR(32) PRIMARY KEY COMMENT '专家ID',
    OPENID VARCHAR(128) UNIQUE COMMENT '微信用户ID',
    EXPERT_NAME VARCHAR(64) NOT NULL COMMENT '专家姓名',
    TITLE VARCHAR(128) COMMENT '职称',
    ORGANIZATION VARCHAR(128) COMMENT '所属机构',
    SPECIALITY VARCHAR(256) COMMENT '专业领域',
    CERTIFICATION VARCHAR(512) COMMENT '资质证明',
    STATUS VARCHAR(32) DEFAULT 'PENDING' COMMENT '状态 PENDING/APPROVED/REJECTED',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 5. 创建索引优化查询性能
CREATE INDEX idx_customer_region ON T_WECHAT_CUSTOMER(REGION_CODE);
CREATE INDEX idx_plant_type ON T_WECHAT_PLANT(PLANT_TYPE, PLANT_CLASS);
CREATE INDEX idx_adoption_user ON T_USER_PLANT_ADOPTION(OPENID);
CREATE INDEX idx_care_record_user ON T_CARE_RECORD(OPENID, CREATE_TIME);
CREATE INDEX idx_behavior_user ON T_USER_BEHAVIOR(OPENID, BEHAVIOR_TYPE);
CREATE INDEX idx_message_user ON T_SYSTEM_MESSAGE(OPENID, IS_READ);

-- 6. 插入基础数据
INSERT INTO T_REGION VALUES 
('110000', '北京市', NULL, 1, '温带大陆性气候', TRUE, NOW()),
('120000', '天津市', NULL, 1, '温带大陆性气候', TRUE, NOW()),
('310000', '上海市', NULL, 1, '亚热带季风气候', TRUE, NOW()),
('440000', '广东省', NULL, 1, '亚热带季风气候', TRUE, NOW());

-- 植物基础分类数据
INSERT INTO T_WECHAT_PLANT (PLANT_TYPE, PLANT_CLASS, PLANT_NUMBER, PLANT_NAME, PLANT_DESCRIPTION, CARE_DIFFICULTY, SUITABLE_REGION, WATER_FREQUENCY, SUNLIGHT_NEED, CREATE_TIME) VALUES
('观叶植物', '常绿植物', 'P001001', '绿萝', '生命力顽强的室内观叶植物，净化空气效果好', '简单', '全国', 3, '散射光', NOW()),
('观叶植物', '常绿植物', 'P001002', '吊兰', '适应性强，容易养护的悬垂植物', '简单', '全国', 2, '散射光', NOW()),
('多肉植物', '景天科', 'P002001', '多肉拼盘', '多种多肉植物组合，造型美观', '简单', '全国', 7, '充足阳光', NOW()),
('观花植物', '草本花卉', 'P003001', '长寿花', '花期长，寓意美好的室内观花植物', '中等', '全国', 5, '充足阳光', NOW());