-- 基于最终决策的数据库设计方案
-- 实体植物 + 用户自主管理 + AI服务支持

-- 1. 用户表（保持原有结构，增加必要字段）
CREATE TABLE T_WECHAT_USER (
    OPENID VARCHAR(128) PRIMARY KEY COMMENT '微信用户唯一标识',
    SUBSCRIBE BOOLEAN DEFAULT TRUE COMMENT '是否关注公众号',
    NICKNAME VARCHAR(1024) COMMENT '用户昵称',
    GENDER VARCHAR(32) COMMENT '性别',
    COUNTRY VARCHAR(128) COMMENT '国家',
    PROVINCE VARCHAR(128) COMMENT '省份',
    CITY VARCHAR(128) COMMENT '城市',
    LANGUAGE VARCHAR(32) COMMENT '语言',
    HEAD_IMG_URL VARCHAR(1024) COMMENT '头像URL',
    SUBSCRIBE_TIME DATETIME COMMENT '关注时间',
    UNIONID VARCHAR(128) COMMENT '联合标识',
    REMARK VARCHAR(1024) COMMENT '备注',
    GROUPID VARCHAR(128) COMMENT '用户分组',
    TAG_LIST VARCHAR(1024) COMMENT '标签列表',
    SUBSCRIBE_SCENE VARCHAR(128) COMMENT '关注场景',
    -- 新增字段
    PLANT_COUNT INT DEFAULT 0 COMMENT '植物数量',
    TOTAL_CARE_DAYS INT DEFAULT 0 COMMENT '累计养护天数',
    LAST_ACTIVE_TIME DATETIME COMMENT '最后活跃时间',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. 用户植物表（用户上传的实体植物）
CREATE TABLE T_USER_PLANT (
    PLANT_ID VARCHAR(32) PRIMARY KEY COMMENT '植物ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    PLANT_NAME VARCHAR(128) NOT NULL COMMENT '植物名称（用户命名）',
    PLANT_TYPE VARCHAR(64) COMMENT 'AI识别的植物类型',
    PLANT_SPECIES VARCHAR(128) COMMENT '具体品种',
    MAIN_IMAGE VARCHAR(512) COMMENT '主要照片',
    LOCATION VARCHAR(256) COMMENT '植物位置（用户填写）',
    GET_METHOD VARCHAR(64) COMMENT '获得方式（购买/赠送/自种等）',
    GET_DATE DATE COMMENT '获得日期',
    DESCRIPTION VARCHAR(1024) COMMENT '植物描述',
    IS_HEALTHY BOOLEAN DEFAULT TRUE COMMENT '是否健康',
    CARE_DIFFICULTY VARCHAR(32) COMMENT '养护难度（AI评估）',
    LAST_CARE_DATE DATE COMMENT '最后养护日期',
    CARE_COUNT INT DEFAULT 0 COMMENT '养护次数',
    STATUS VARCHAR(32) DEFAULT 'ACTIVE' COMMENT '状态（ACTIVE/DORMANT/DEAD）',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_user_plant(OPENID),
    INDEX idx_plant_type(PLANT_TYPE),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID)
);

-- 3. 养护记录表
CREATE TABLE T_CARE_RECORD (
    RECORD_ID VARCHAR(32) PRIMARY KEY COMMENT '记录ID',
    PLANT_ID VARCHAR(32) NOT NULL COMMENT '植物ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    CARE_TYPE VARCHAR(32) NOT NULL COMMENT '养护类型（WATER/FERTILIZE/PRUNE/OBSERVE/REPOT）',
    CARE_NOTE VARCHAR(1024) COMMENT '养护备注',
    IMAGES VARCHAR(2048) COMMENT '照片记录（多张图片URL，逗号分隔）',
    WEATHER VARCHAR(32) COMMENT '天气情况',
    PLANT_STATUS VARCHAR(32) COMMENT '植物状态记录',
    NEXT_CARE_DATE DATE COMMENT '下次养护建议日期',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_plant_care(PLANT_ID, CREATE_TIME),
    INDEX idx_user_care(OPENID, CREATE_TIME),
    FOREIGN KEY (PLANT_ID) REFERENCES T_USER_PLANT(PLANT_ID),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID)
);

-- 4. AI问答记录表
CREATE TABLE T_AI_CONSULTATION (
    CONSULTATION_ID VARCHAR(32) PRIMARY KEY COMMENT '咨询ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    PLANT_ID VARCHAR(32) COMMENT '相关植物ID（可选）',
    QUESTION_TYPE VARCHAR(32) NOT NULL COMMENT '问题类型（CARE/DISEASE/IDENTIFY/GENERAL）',
    QUESTION_TEXT VARCHAR(2048) COMMENT '问题文本',
    QUESTION_IMAGES VARCHAR(1024) COMMENT '问题图片',
    AI_RESPONSE TEXT COMMENT 'AI回复内容',
    RESPONSE_TIME INT COMMENT '响应时间（毫秒）',
    USER_RATING INT COMMENT '用户评分（1-5）',
    IS_HELPFUL BOOLEAN COMMENT '是否有帮助',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_user_consultation(OPENID, CREATE_TIME),
    INDEX idx_plant_consultation(PLANT_ID),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID),
    FOREIGN KEY (PLANT_ID) REFERENCES T_USER_PLANT(PLANT_ID)
);

-- 5. 社区动态表
CREATE TABLE T_COMMUNITY_POST (
    POST_ID VARCHAR(32) PRIMARY KEY COMMENT '动态ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '发布用户ID',
    PLANT_ID VARCHAR(32) COMMENT '相关植物ID',
    CONTENT VARCHAR(2048) NOT NULL COMMENT '动态内容',
    IMAGES VARCHAR(2048) COMMENT '图片列表',
    LOCATION VARCHAR(256) COMMENT '位置信息',
    TOPIC_TAGS VARCHAR(512) COMMENT '话题标签',
    VIEW_COUNT INT DEFAULT 0 COMMENT '浏览次数',
    LIKE_COUNT INT DEFAULT 0 COMMENT '点赞次数',
    COMMENT_COUNT INT DEFAULT 0 COMMENT '评论次数',
    IS_FEATURED BOOLEAN DEFAULT FALSE COMMENT '是否精选',
    STATUS VARCHAR(32) DEFAULT 'PUBLISHED' COMMENT '状态（PUBLISHED/HIDDEN/DELETED）',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_user_post(OPENID, CREATE_TIME),
    INDEX idx_plant_post(PLANT_ID),
    INDEX idx_featured_post(IS_FEATURED, CREATE_TIME),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID),
    FOREIGN KEY (PLANT_ID) REFERENCES T_USER_PLANT(PLANT_ID)
);

-- 6. 动态互动表（点赞、评论）
CREATE TABLE T_POST_INTERACTION (
    INTERACTION_ID VARCHAR(32) PRIMARY KEY COMMENT '互动ID',
    POST_ID VARCHAR(32) NOT NULL COMMENT '动态ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    INTERACTION_TYPE VARCHAR(32) NOT NULL COMMENT '互动类型（LIKE/COMMENT）',
    CONTENT VARCHAR(1024) COMMENT '评论内容（点赞时为空）',
    REPLY_TO VARCHAR(32) COMMENT '回复的评论ID',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_post_interaction(POST_ID, INTERACTION_TYPE),
    INDEX idx_user_interaction(OPENID, CREATE_TIME),
    UNIQUE KEY uk_user_like(POST_ID, OPENID, INTERACTION_TYPE),
    FOREIGN KEY (POST_ID) REFERENCES T_COMMUNITY_POST(POST_ID),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID)
);

-- 7. 植物知识库表（AI生成 + 用户贡献）
CREATE TABLE T_PLANT_KNOWLEDGE (
    KNOWLEDGE_ID VARCHAR(32) PRIMARY KEY COMMENT '知识ID',
    PLANT_TYPE VARCHAR(64) NOT NULL COMMENT '植物类型',
    TITLE VARCHAR(256) NOT NULL COMMENT '标题',
    CONTENT TEXT NOT NULL COMMENT '内容',
    IMAGES VARCHAR(1024) COMMENT '配图',
    SOURCE VARCHAR(32) DEFAULT 'AI' COMMENT '来源（AI/USER/EXPERT）',
    AUTHOR_OPENID VARCHAR(128) COMMENT '作者用户ID',
    VIEW_COUNT INT DEFAULT 0 COMMENT '浏览次数',
    LIKE_COUNT INT DEFAULT 0 COMMENT '点赞次数',
    IS_VERIFIED BOOLEAN DEFAULT FALSE COMMENT '是否已验证',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_plant_knowledge(PLANT_TYPE),
    INDEX idx_knowledge_source(SOURCE, IS_VERIFIED),
    FOREIGN KEY (AUTHOR_OPENID) REFERENCES T_WECHAT_USER(OPENID)
);

-- 8. 系统参数表（保持原有结构）
CREATE TABLE T_SYSTEM_PARAMETER (
    PARA_INDEX VARCHAR(32) PRIMARY KEY COMMENT '参数索引',
    PARA_NAME VARCHAR(64) COMMENT '参数名称',
    PARA_CONTENT VARCHAR(2048) COMMENT '参数内容',
    PARA_TYPE VARCHAR(32) DEFAULT 'STRING' COMMENT '参数类型',
    PARA_REMARK VARCHAR(1024) COMMENT '参数备注',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    LAST_MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 9. 用户反馈表
CREATE TABLE T_USER_FEEDBACK (
    FEEDBACK_ID VARCHAR(32) PRIMARY KEY COMMENT '反馈ID',
    OPENID VARCHAR(128) NOT NULL COMMENT '用户ID',
    FEEDBACK_TYPE VARCHAR(32) NOT NULL COMMENT '反馈类型（BUG/SUGGESTION/COMPLAINT/PRAISE）',
    TITLE VARCHAR(256) COMMENT '反馈标题',
    CONTENT VARCHAR(2048) NOT NULL COMMENT '反馈内容',
    IMAGES VARCHAR(1024) COMMENT '截图或照片',
    CONTACT_INFO VARCHAR(256) COMMENT '联系方式',
    STATUS VARCHAR(32) DEFAULT 'PENDING' COMMENT '处理状态（PENDING/PROCESSING/RESOLVED/CLOSED）',
    ADMIN_REPLY VARCHAR(1024) COMMENT '管理员回复',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    RESOLVE_TIME DATETIME COMMENT '解决时间',
    
    INDEX idx_user_feedback(OPENID, CREATE_TIME),
    INDEX idx_feedback_status(STATUS, CREATE_TIME),
    FOREIGN KEY (OPENID) REFERENCES T_WECHAT_USER(OPENID)
);

-- 插入基础系统参数
INSERT INTO T_SYSTEM_PARAMETER VALUES
('AI_MODEL_TYPE', 'AI模型类型', 'gpt-3.5-turbo', 'STRING', '当前使用的AI模型', TRUE, NOW()),
('PLANT_IDENTIFY_API', '植物识别API', 'baidu', 'STRING', '植物识别服务提供商', TRUE, NOW()),
('MAX_PLANT_PER_USER', '用户最大植物数', '50', 'INTEGER', '单个用户最多可添加的植物数量', TRUE, NOW()),
('IMAGE_MAX_SIZE', '图片最大尺寸', '2048', 'INTEGER', '上传图片最大像素', TRUE, NOW()),
('CARE_REMIND_DAYS', '养护提醒天数', '3', 'INTEGER', '超过多少天未养护时提醒', TRUE, NOW());